### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Mx74** [booya-at/paraBEM#4]
Hello,

Dependencies installion is ok. 
Initialization run smoothly.
But "sudo make install  -j2" gives:

`[ 88%] Building CXX object src/python/CMakeFiles/_paraBEM.dir/paraBEM_ext.cpp.o
../paraBEM/src/python/paraBEM_ext.cpp:255:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(_paraBEM, m) {
                ^
src/python/CMakeFiles/_paraBEM.dir/build.make:62 : la recette pour la cible « src/python/CMakeFiles/_paraBEM.dir/paraBEM_ext.cpp.o » a échouée
make[2]: *** [src/python/CMakeFiles/_paraBEM.dir/paraBEM_ext.cpp.o] Erreur 1
CMakeFiles/Makefile2:304 : la recette pour la cible « src/python/CMakeFiles/_paraBEM.dir/all » a échouée
make[1]: *** [src/python/CMakeFiles/_paraBEM.dir/all] Erreur 2
Makefile:129 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
`

**Comment by looooo** [comment]
I guess pybind11 is missing. Easiest is installation via pip:
```sudo pip install pybind11```

**Comment by Mx74** [comment]
I did install pybind11-dev via apt-get.

Tried again with pip, but still : 

`Requirement already satisfied: pybind11 in /usr/local/lib/python2.7/dist-packages
max@max-VirtualBox:~/paraBEM/build$ sudo make install  -j2
[ 77%] Built target pm
[ 88%] Building CXX object src/python/CMakeFiles/_paraBEM.dir/paraBEM_ext.cpp.o
../paraBEM/src/python/paraBEM_ext.cpp:255:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(_paraBEM, m) {
                ^
src/python/CMakeFiles/_paraBEM.dir/build.make:62 : la recette pour la cible « src/python/CMakeFiles/_paraBEM.dir/paraBEM_ext.cpp.o » a échouée
make[2]: *** [src/python/CMakeFiles/_paraBEM.dir/paraBEM_ext.cpp.o] Erreur 1
CMakeFiles/Makefile2:304 : la recette pour la cible « src/python/CMakeFiles/_paraBEM.dir/all » a échouée
make[1]: *** [src/python/CMakeFiles/_paraBEM.dir/all] Erreur 2
Makefile:129 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
`

**Comment by looooo** [comment]
maybe it's a old version. Pip normally has a newer version. To you know the version of pybind11? I guess 2.2 or newer should be fine.

**Comment by looooo** [comment]
ah sorry I didn't see you updated with pip...

I just tried pip my self. and I guess pip doesn't install the cmake stuff. So it could be that there are two pybind11 packages installed and cmake still finds the system version.

Thats difficult. Maybe you can try commenting out the find-package(pybind11) line in the CmakeLists.txt. Maybe this way the pip package is used.

**Comment by Mx74** [comment]
Yep, apt-get install 2.0.1-4. 
I purged it, and yep, cmake doesn't like pip install..

commenting this line doesn't work.

`Requirement already satisfied: pybind11 in /usr/local/lib/python2.7/dist-packages
max@max-VirtualBox:~/paraBEM/build$ sudo make install  -j2
-- python version set: 
3.3.4
-- python-py27
-- installing to 
CMake Error at src/python/CMakeLists.txt:15 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
`

**Comment by Mx74** [comment]
Yes, apt-get install 2.0.1-4
Commenting this line doesn't work. 
I have to find out another way to install pybind11 v2.2

**Comment by looooo** [comment]
nearly ;)

the problem is that the ubuntu version is too old and the pip version doesn't ship the cmake stuff and therefor the macro "pybind11_add_module" is not available.

I tried it my self on ubuntu:
pybind11
```bash
git clone https://github.com/pybind/pybind11
cd pybind11
mkdir build
cd build
cmake .. -DPYBIND11_PYTHON_VERSION=2.7  # maybe some additional stuff is needed, in my case py_test which I installed with pip
sudo cmake install
```

paraBEM
```bash
git clone https://github.com/booya-at/paraBEM
cd paraBEM
mkdir build
cd build
cmake -Dpy=2.7 -DCMAKE_CXX_FLAGS="-std=c++11 -fPIC" -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install
```

**Comment by Mx74** [comment]
Great !! Thanks a lot :+1: 

![capture d ecran de 2018-04-03 10-13-28](https://user-images.githubusercontent.com/23337492/38237593-f0f6f2a0-3727-11e8-866a-d556d7d74ac4.png)

**Comment by Mx74** [comment]
Great ! Thanks a lot :+1: 

![capture d ecran de 2018-04-03 10-18-12](https://user-images.githubusercontent.com/23337492/38237790-67b7de40-3728-11e8-88fe-65fe4f6217fc.png)

**Comment by Mx74** [comment]
I forgot to mention, during the installation process, scipy had to be installed. 
To add in the dependancies.

**Comment by looooo** [comment]
nice! and thanks for the hint. I added scipy to the dependencies
https://github.com/booya-at/paraBEM/commit/72bbdc8388a1944acfff536e0127259202d8da98#diff-04c6e90faac2675aa89e2176d2eec7d8R20
